-- Run once as the local database owner; passwords are supplied separately via psql.
CREATE ROLE grading_owner LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE grading_web LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE grading_operator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE grading_admin LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
REVOKE ALL ON DATABASE grading FROM PUBLIC;
GRANT CONNECT ON DATABASE grading TO grading_owner, grading_web, grading_operator, grading_admin;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO grading_owner;
